const constants = {
  userDir: "nextcasts",
  name: "nextcast",
  dataDirname: `.nextcast`,
  dataFileName: "data.json",
  rewritesFileName: "rewrites.json",
  errorsFileName: "errors.json",
  warningsFileName: "warnings.json",
  collectionFileName: "collection.json",
  hashDir: ".hashes",
  watchExcludes: [
    "tsconfig.json",
    "tailwind.config.js",
    "tailwind.config.cjs",
    "tailwind.config.mjs",
    "tailwind.config.ts",
    "next.config.js",
    "next.config.mjs",
    "next-env.d.ts",
    "package-lock.json",
    "package.json",
    "yarn.lock",
    "yarn-error.log",
    ".yarn/**",
    "postcss.config.js",
    "postcss.config.ts",
    "README.md",
    ".wrangler/**",
    ".git/**",
    ".github/**",
    "dist/**",
    "build/**",
    "out/**",
    ".next/**",
    "node_modules/**",
    `nextcasts/**`,
  ],
};

export default constants;
