name: ci

on:
  push:
    branches: ["release"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.1
      - run: npm ci --omit=dev
      - run: npm run ci:build
      - run: npm run ci:test
